@startuml
skinparam classAttributeIconSize 0


class CartItem {
  - articleId : int
  - name : string
  - quantity : int
  - price : float
  + CartItem(articleId : int, name : string, quantity : int, price : float)
  + <get>articleId() : int
  + <get,set>quantity() : int
  + <get,set>price() : int
  + <get>total() : int
}

class Cart {
  - items : CartItem[]
  + Cart(items: CartItem[])
  + <get,set>items() : CartItem[]
  + total() : int
  + count(placeholder : boolean = False) : int
  + add(item : CartItem)
}

exception CartItemException {
}

exception InvalidArticleIdException {
}

exception InvalidQuantityException {
}

exception InvalidPriceException {
}

exception CartException {
}

exception EmptyCartException {
}

exception UpdateCartException {
}


Cart ..> CartItem
InvalidArticleIdException --|> CartItemException
InvalidQuantityException --|> CartItemException
InvalidPriceException --|> CartItemException
InvalidArticleIdException --+ CartItem
InvalidQuantityException --+ CartItem
InvalidPriceException --+ CartItem
EmptyCartException --|> CartException
UpdateCartException --|> CartException
EmptyCartException --+ Cart
UpdateCartException --+ Cart
@enduml